update phpdotenv
shyim/store-plugin-installer pull request #13
Opened 2019-01-10 14:34 UTC by arosenhagen

update vlucas/phpdotenv v3.1 and switch to new native constructor call

2019-01-10 14:36 UTC, shyim commented
Would this not break the compability to the composer project? It requires version 2
https://github.com/shopware/composer-project/blob/master/composer.json#L23

2019-01-10 14:42 UTC, arosenhagen commented
good catch - I made an [according PR](https://github.com/shopware/composer-project/pull/32) to that repo too. 👍

2019-01-10 14:46 UTC, shyim commented
I don't really like to update that. If someone using still the old composer template, it would break on that installations. Maybe require version 2 or 3 and make a small version switch?

2019-02-25 21:31 UTC, shyim commented
The template has been updated. Can you add a case to support v2 and v3?
This composer extension has still to support old composer-project templates :)

2019-02-26 22:07 UTC, shyim requested changes

2019-02-26 22:07 UTC, shyim commented on README.md
> +        "vlucas/phpdotenv": "^3.1",
We need here a or condition, ~2.0 || ~3.1

2019-03-02 16:30 UTC, shyim commented on composer.json
> +        "vlucas/phpdotenv": "^3.3",
also here

2019-03-20 17:12 UTC, merged

2019-03-20 17:13 UTC, shyim commented
Thanks! 💙